### ISSUE TITLE
Superfluous spaces

### ISSUE THREAD

**Issue by iambryanhaney** [learn-co-curriculum/programming-univbasics-program-with-expressions#5]
**sun_message** contains a leading space in both variations, obviating the delimiting space in the final strings:

`sun_message = sun_is_dangerous ? ' and watch out for heat stroke!' : ' and bask in this fine weather.'`

`"Hello, #{name}! With a rain chance of #{rain_percentage * 100}% and a temperature of #{temperature_in_c}C we recommend that you #{rain_message} #{sun_message}"`

...

`sun_message = sun_is_dangerous ? ' watch out for heat stroke!' : ' bask in this
fine weather.'`
 
`"Hello, #{name}! With a rain chance of #{rain_percentage * 100}% and a temperature of #{temperature_in_c}C we recommend that you #{rain_message} and #{sun_message}"`

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
